# Generated by Django 3.1.1 on 2020-12-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
