# Generated by Django 3.1.1 on 2020-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20201209_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
