# Generated by Django 3.1.1 on 2020-12-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20201209_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='rating',
            field=models.CharField(default='7.0', max_length=3),
        ),
    ]
