# Generated by Django 3.1.1 on 2020-12-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_tours_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='review_title',
            field=models.CharField(default='good', max_length=10),
        ),
    ]
