# Generated by Django 3.1.1 on 2020-12-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_tours_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='review_number',
            field=models.CharField(default='10', max_length=5),
        ),
    ]
