# Generated by Django 3.1.1 on 2020-12-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_tours_review_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='trip_duration',
            field=models.CharField(default='3N2D', max_length=10),
        ),
    ]
