# Generated by Django 3.1.1 on 2020-12-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_tours_trip_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tourImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('tours', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='offers.tours')),
            ],
        ),
    ]
