# Generated by Django 3.1.1 on 2020-12-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20201210_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='create_at',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
