# Generated by Django 3.1.1 on 2020-12-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_deal_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
