# Generated by Django 3.1.1 on 2020-12-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_auto_20201211_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='email',
            field=models.EmailField(default='none-email', max_length=250),
        ),
    ]
