# Generated by Django 3.1.1 on 2020-12-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_auto_20201216_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='email',
        ),
    ]
