# Generated by Django 3.1.1 on 2020-12-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0008_tourimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('tours', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='offers.tours')),
            ],
        ),
    ]
