# Generated by Django 3.1.1 on 2021-01-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
